version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: aquasense
      POSTGRES_PASSWORD: aquapassword
      POSTGRES_DB: aquasense_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
