import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#0f172a",
        "surface-dim": "#020617",
        "surface-bright": "#1e293b",
        "surface-container-lowest": "#020617",
        "surface-container-low": "#0f172a",
        "surface-container": "#1e293b",
        "surface-container-high": "#334155",
        "surface-container-highest": "#475569",
        "on-surface": "#f8fafc",
        "on-surface-variant": "#cbd5e1",
        "inverse-surface": "#f8fafc",
        "inverse-on-surface": "#0f172a",
        outline: "#64748b",
        "outline-variant": "#334155",
        "surface-tint": "#38bdf8",
        primary: "#38bdf8",
        "on-primary": "#0c4a6e",
        "primary-container": "#0369a1",
        "on-primary-container": "#e0f2fe",
        "inverse-primary": "#0c4a6e",
        secondary: "#2dd4bf",
        "on-secondary": "#042f2e",
        "secondary-container": "#0f766e",
        "on-secondary-container": "#ccfbf1",
        tertiary: "#818cf8",
        "on-tertiary": "#312e81",
        "tertiary-container": "#4338ca",
        "on-tertiary-container": "#e0e7ff",
        error: "#ef4444",
        "on-error": "#450a0a",
        "error-container": "#b91c1c",
        "on-error-container": "#fef2f2",
        "primary-fixed": "#bae6fd",
        "primary-fixed-dim": "#7dd3fc",
        "on-primary-fixed": "#082f49",
        "on-primary-fixed-variant": "#0369a1",
        "secondary-fixed": "#99f6e4",
        "secondary-fixed-dim": "#5eead4",
        "on-secondary-fixed": "#042f2e",
        "on-secondary-fixed-variant": "#0f766e",
        "tertiary-fixed": "#e0e7ff",
        "tertiary-fixed-dim": "#c7d2fe",
        "on-tertiary-fixed": "#312e81",
        "on-tertiary-fixed-variant": "#4338ca",
        background: "#0f172a",
        "on-background": "#f8fafc",
        "surface-variant": "#1e293b",
      },
      fontFamily: {
        "headline-lg": ["Lexend", "sans-serif"],
        "headline-lg-mobile": ["Lexend", "sans-serif"],
        "headline-md": ["Lexend", "sans-serif"],
        "headline-sm": ["Lexend", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600", letterSpacing: "-0.02em" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "32px",
        xl: "48px",
        gutter: "20px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        full: "9999px",
      },
      boxShadow: {
        'premium': '0 10px 40px -10px rgba(0, 52, 97, 0.08), 0 1px 3px rgba(0, 52, 97, 0.05)',
        'premium-hover': '0 20px 40px -10px rgba(0, 52, 97, 0.12), 0 1px 3px rgba(0, 52, 97, 0.05)',
        'glass': '0 8px 32px 0 rgba(0, 52, 97, 0.07)',
      },
      backgroundImage: {
        'water-mesh': 'radial-gradient(at 0% 0%, hsla(215,100%,15%,1) 0px, transparent 50%), radial-gradient(at 100% 0%, hsla(220,100%,10%,1) 0px, transparent 50%), radial-gradient(at 100% 100%, hsla(210,100%,20%,1) 0px, transparent 50%), radial-gradient(at 0% 100%, hsla(225,100%,12%,1) 0px, transparent 50%)',
      }
    },
  },
  plugins: [],
} satisfies Config;
