import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f8f9ff",
        "surface-dim": "#d1dbec",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eef4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dfe9fa",
        "surface-container-highest": "#d9e3f4",
        "on-surface": "#121c28",
        "on-surface-variant": "#424750",
        "inverse-surface": "#27313e",
        "inverse-on-surface": "#eaf1ff",
        outline: "#727781",
        "outline-variant": "#c2c6d1",
        "surface-tint": "#27609d",
        primary: "#003461",
        "on-primary": "#ffffff",
        "primary-container": "#004b87",
        "on-primary-container": "#8abcff",
        "inverse-primary": "#a3c9ff",
        secondary: "#006a6a",
        "on-secondary": "#ffffff",
        "secondary-container": "#90efef",
        "on-secondary-container": "#006e6e",
        tertiary: "#2c3439",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#424b50",
        "on-tertiary-container": "#b2bbc0",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d3e4ff",
        "primary-fixed-dim": "#a3c9ff",
        "on-primary-fixed": "#001c38",
        "on-primary-fixed-variant": "#004882",
        "secondary-fixed": "#93f2f2",
        "secondary-fixed-dim": "#76d6d5",
        "on-secondary-fixed": "#002020",
        "on-secondary-fixed-variant": "#004f4f",
        "tertiary-fixed": "#dbe4ea",
        "tertiary-fixed-dim": "#bfc8ce",
        "on-tertiary-fixed": "#141d21",
        "on-tertiary-fixed-variant": "#3f484d",
        background: "#f8f9ff",
        "on-background": "#121c28",
        "surface-variant": "#d9e3f4",
      },
      fontFamily: {
        "headline-lg": ["Lexend", "sans-serif"],
        "headline-lg-mobile": ["Lexend", "sans-serif"],
        "headline-md": ["Lexend", "sans-serif"],
        "headline-sm": ["Lexend", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600", letterSpacing: "-0.02em" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "32px",
        xl: "48px",
        gutter: "20px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        full: "9999px",
      },
      boxShadow: {
        'premium': '0 10px 40px -10px rgba(0, 52, 97, 0.08), 0 1px 3px rgba(0, 52, 97, 0.05)',
        'premium-hover': '0 20px 40px -10px rgba(0, 52, 97, 0.12), 0 1px 3px rgba(0, 52, 97, 0.05)',
        'glass': '0 8px 32px 0 rgba(0, 52, 97, 0.07)',
      },
      backgroundImage: {
        'water-mesh': 'radial-gradient(at 0% 0%, hsla(205,100%,92%,1) 0px, transparent 50%), radial-gradient(at 100% 0%, hsla(180,100%,94%,1) 0px, transparent 50%), radial-gradient(at 100% 100%, hsla(213,100%,92%,1) 0px, transparent 50%), radial-gradient(at 0% 100%, hsla(190,100%,94%,1) 0px, transparent 50%)',
      }
    },
  },
  plugins: [],
} satisfies Config;
